### ISSUE TITLE
please add a transpiled live test

### ISSUE THREAD

**Issue by AndyOGo** [ungap/custom-elements-builtin#1]
The old polyfill [`built-in-element` offers a transpiled](https://github.com/WebReflection/built-in-element#compatible-with-) live test too:
https://webreflection.github.io/built-in-element/test/es5/

May I asked you to add it here too.

The current ES2015 Live test does of course not work in IE11 and throws:
```sh
SCRIPT1002: Syntax error
File: my-button.js, Line: 3, Column: 3
```

**Comment by WebReflection** [comment]
There you go: https://ungap.github.io/custom-elements-builtin/test/es5/

**Comment by AndyOGo** [comment]
awesome thank you very much
