### ISSUE TITLE
crashes when you call cloneNode on <meta>

### ISSUE THREAD

**Issue by kamholz** [ungap/custom-elements-builtin#24]
If this polyfill is installed and any JS code calls `cloneNode` on a `<meta>` element, the browser will crash (tested on Safari but presumably others). This is because it will call the polyfill's wrapped `cloneNode`, which will find the meta element's `.content` attribute, treat it like a template, and call `setupSubNodes` on the text value of the content attribute. `setupSubNodes` in turn calls `.querySelectorAll` on the text, which isn't possible, and causes an exception. Cloning the meta element (presumably) has nothing to do with custom elements, but the polyfill should not break unrelated valid DOM calls.

I tried to fix this with #23, but as you correctly pointed out, the logic doesn't work because nodeType 11 is a document fragment and template elements are nodeType 1 (their `.content` points to a document fragment, which is where I got confused). I suggest the following proper fix in `wrapOriginal`:

```js
if (result.nodeType === 1 || result.nodeType === 11)
  setupSubNodes(result.content instanceof Node ? result.content : result, setupIfNeeded);
```

This is enough to fix the `<meta>` case. For the `.innerHTML` setter (index.js line 116) it's not relevant for `<meta>` because it has no child nodes. However, since this is a polyfill and its behavior should be strictly limited to the features it's adding, and it's not really futureproof that `.content` will always contain a `Node` if present, it seems like a good idea to check there too.

**Comment by WebReflection** [comment]
could you please add a test case so I can work on it?

I still really much would like to know why you are extending meta, if possible, as this looks like a very niche use case, and, the goal of ungap is to be pragmatic, small, and fast, not to be 100% specs compliant.

regardless, I agree I should fix this, but until I can test it's broken (i.e. test case) I won't likely fix this sooner, thanks.

**Comment by kamholz** [comment]
I am not extending meta! I am calling cloneNode on meta in *unrelated* code. The polyfill shouldn't break a perfectly normal and innocent call to cloneNode.

I can make a test case but will have to look into how the tests are written.

**Comment by kamholz** [comment]
OK, so to test it, should be enough to do the following using index.html in the test dir:

```js
document.querySelector("meta[name='viewport']").cloneNode();
```

**Comment by WebReflection** [comment]
Thanks

**Comment by WebReflection** [comment]
Fixed 👋

**Comment by kamholz** [comment]
Looks good, thanks!
