### ISSUE TITLE
Error : undefined is not an object (evaluating '(HTMLBuiltIn.prototype = tmp.prototype).constructor..

### ISSUE THREAD

**Issue by Ballpin** [ungap/custom-elements-builtin#26]
Hello,

I tried this polyfill and it works great on some enviorments but on others where more polyfills are included (from corejs3) i keep getting this error.

`TypeError: undefined is not an object (evaluating '(HTMLBuiltIn.prototype = tmp.prototype).constructor = HTMLBuiltIn')` 

Any idea how to solve it?

EDIT: I tried to solve it myself but had no luck.

**Comment by WebReflection** [comment]
File a bug there?

**Comment by Ballpin** [comment]
> File a bug there?

What do you mean? Im not really following.

**Comment by Ballpin** [comment]
> File a bug there?

Sorry about my earlier message. I understood what you ment after i wrote it. 

It is on my own project where it is not working. What is really weird when i import it to Storybook it works well, but in my current project it is not working even though i have the same config (as the one im using in storybook) where it was working.

Even when i remove all html code in the server, same error keeps popping up. Im using django btw

**Comment by WebReflection** [comment]
include this polyfill before anything else, never do the other way around. If that still breaks, you gotta give me something more than "_Im using django btw_", as this is *client side* JavaScript, and it has nothing to do with the server side/BE of choice.

**Comment by Ballpin** [comment]
Yes you are right. I apologise.. i found the my error now. I was so blind in my own code and totally missed one line.

**Comment by WebReflection** [comment]
Glad you solved. If it was a particular trick, please share, so others searching through bugs *might* have a solution already 👋

**Comment by Ballpin** [comment]
The trick was pretty simple, go away from the computer for a few seconds and then look at your code again. :-)

**Comment by WebReflection** [comment]
Huh, that often works for me as well 👍
