### ISSUE TITLE
Safari 14 not throwing on test

### ISSUE THREAD

**Issue by luwes** [ungap/custom-elements-builtin#27]
Seems Safari 14 is not throwing on this test anymore 😫

`customElements.define('built-in', document.createElement('p').constructor, {'extends':'p'});`

**Comment by WebReflection** [comment]
yeah it's a bit more complicated these days:
https://github.com/WebReflection/custom-elements/blob/master/template/index.js

I should probably update the README, but the long story short is that this is the polyfill that feature-detect them all:
https://github.com/ungap/custom-elements#readme

it also patches modern browsers due latter changes to the whenDefined resolution

**Comment by luwes** [comment]
thanks! I still kinda prefer to have a small inline JS test before including polyfills (extra requests)

also a little heads up, those 302 redirects of unpkg.com regularly hang on my end. not sure if it's a real issue or not but they can really add a few seconds to the page load.

**Comment by WebReflection** [comment]
> thanks! I still kinda prefer to have a small inline JS test before including polyfills (extra requests)

understood, but the other fix also other browsers here and there ... just saying

> also a little heads up, those 302 redirects of unpkg.com

I have noting to do with unpkg.com, I just find it super convenient for demos purposes, but I've never mentioned you should use that in production
