### ISSUE TITLE
connectedCallback not called when also using webcomponentsjs polyfill

### ISSUE THREAD

**Issue by BryceBeagle** [ungap/custom-elements-builtin#3]
As a preface: I'm new to the Javascript world, so please let me know if anything I'm saying is dumb/wrong. The screenshots attached are because I do not know of a proper way to reference sections de-minimized/prettified code. If necessary I can provide more detail.

I'm attempting to use custom components in a Chrome Extension and have been forced to use the [webcomponentsjs polyfill](https://github.com/webcomponents/webcomponentsjs). It does provide support for extending builtins and I am using this project for that. However, the connectedCallback function is not called on a custom element class that extends a builtin. 

I did a little bit of tinkering in the debugger, and I have determined that the webcomponents polyfill does not execute the callback because the class does not have an attribute `__CE_state` set to `1` (see terminal for values):

![image](https://user-images.githubusercontent.com/5437880/51661885-03f52200-1f67-11e9-8d24-7e32df433869.png)

This is opposed to a custom HTMLElement where this _is_ set to `1`:

![image](https://user-images.githubusercontent.com/5437880/51661971-40288280-1f67-11e9-92d2-1955ed4c31bf.png)

This `__CE_state` attribute appears to be set within the webcomponents polyfill:

![image](https://user-images.githubusercontent.com/5437880/51662108-a44b4680-1f67-11e9-89af-c72a578498de.png)

Is there a way custom-elements-builtin can work with the webcomponentsjs polyfill or am I going to need to find another solution if I need to use the polyfill?

**Comment by WebReflection** [comment]
> I'm attempting to use custom components in a Chrome Extension

Chrome supports Custom Elements natively so you don't need any polyfill.

However, in case you really do, the battle tested one that even Google AMP project is using, as well as Stencil JS, AFrame, and others, is [document-register-element](https://github.com/WebReflection/document-register-element), not the other one you have been forced to use

> and have been forced to use the webcomponentsjs polyfill. 

what does that even mean?

> It does provide support for extending builtins and I am using this project for that.

I wouldn't know, but it makes no sense to hook into their internals here 'cause this is a stand-alone project.

> This __CE_state attribute appears to be set within the webcomponents polyfill:

This is another project, I don't know/care about `__CE_state` here, [as you can see](https://github.com/ungap/custom-elements-builtin/blob/master/index.js), 'cause that's third parts internal and I have no intention to do anything with that.

> Is there a way custom-elements-builtin can work with the webcomponentsjs polyfill

This polyfill works with native customElements, or proper polyfills such document-register-element that already patches CE v1 with built-ins.

Accordingly, you should probably file an issue in their polyfill asking to support built-ins.

> am I going to need to find another solution if I need to use the polyfill?

which one? the one you are forced to use or this one? In any case, I don't know other solutions but if you find one I guess that's an option 👋

**Comment by WebReflection** [comment]
P.S. if this helps with any internal political decision, at [ABP](https://adblockplus.org) we use document-register-element polyfill, so it's one of those known libraries nobody would argue about, in either Chrome or Firefox extensions store.

**Comment by BryceBeagle** [comment]
Hey, thanks for the response. Sorry, "forced" was probably not the right term to use. I was (apparently incorrectly) under the assumption that if I were to need a polyfill, the webcomponentsjs one was the one to use. (It's even linked to on [the Google Developers page](https://developers.google.com/web/fundamentals/web-components/customelements#historysupport) on custom elements.) I didn't realize there were other options. 

You mention that Chrome has support for custom elements natively, but I just could not get them working properly in my extension. I get the same issue that's documented in [this StackOverflow question](https://stackoverflow.com/questions/42800035/why-cant-you-create-custom-elements-in-chrome-extensions). Do you have any tricks to get them working without a polyfill in an extension?

In the meantime, I'll be giving document-register-element a shot. Thanks again.

**Comment by WebReflection** [comment]
@BryceBeagle everything is written in here:
https://github.com/WebReflection/document-register-element#how-to-polyfill-custom-elements-v1

If you have `window.customElements` already you don't need any polyfill to use this one, and this one is about using V1, where available, to extend V1 itself, specially on Safari, the only one left behind with built in extends.

Every browser that won't have customElements will never show a warning about anything.

If for some reason you cannot use that approach, you can `var dre = require('document-register-elements/pony');` and then `if (!window.customElements) dre(window);`

In all cases, you won't have any warning.
