### ISSUE TITLE
attributeChanged callback is delayed in Safari

### ISSUE THREAD

**Issue by MikeVaz** [ungap/custom-elements-builtin#4]
This happens when manually creating an instance of a custom element, adding it to the DOM, changing attribute and removing from the DOM. 

```javascript
    class MyButton extends HTMLButtonElement {
        constructor() {
            super();
        }
        static get observedAttributes() { return ['test']; }
        disconnectedCallback() {
            this._flag += ',disconnected';
        }
        connectedCallback() {
            this._flag += ',connected';
        }
        attributeChangedCallback() {
            this._flag += ',attributeChanged';
        }
    }

    customElements.define('my-button', MyButton, { extends: 'button' });
    var el = document.createElement('button', { is: 'my-button' });
    el._flag = 'created';
    document.body.appendChild(el); // flag = created,connected
    el.setAttribute('test', 1); // flag = created,connected,attributeChanged
    document.body.removeChild(el); // flag = created,connected,attributeChanged,disconnected
    requestAnimationFrame(function () {
        console.log(el._flag, el._flag == 'created,connected,attributeChanged,disconnected');
    })	
```

In Safari `attributeChangedCallback` will happen after element is removed. 

https://jsfiddle.net/0Lze51xm/

MacOS Safari Version 11.1.2 (13605.3.8)

**Comment by MikeVaz** [comment]
It is wired since now you'd have more inconsistencies like in IE11 life-cycle events are asynchronous because Mutation Observer is used everywhere. In Chrome they are synchronous. In Safari some are asynchronous when customizing built-ins because Mutation Observer is used for attribute change.

**Comment by WebReflection** [comment]
This is a won't fix as there are no solutions since sync events are deprecated.
If you need to be sure a node is live when an attribute changes, check if it's document contains it.
