### ISSUE TITLE
constructor cave-eat 

### ISSUE THREAD

**Issue by hagb4rd** [ungap/custom-elements-builtin#5]
hi andrea. on your cave-eat thing: not sure i get the context here, but usually it should be fine to have the factory trigger its child method. like document does, right? 

```js
class Scene extends WeakSet {
	constructor() {
		super()
	}
	add(node){
		if(!this.has(node)) {
			super.add(node);
			node.connectedCallback();
		}
	}
	remove(node){
		if(this.has(node)) {
			super.remove(node);
			node.disconnectedCallback();
		}
	}
}

class MyButton extends HTMLButtonElement {
	constructor() {
		this.live=false;
	}
  connectedCallback() {
    this.live=!this.live;
  }
  disconnectedCallback() {
    this.live=!this.live;
  }
}
```
P.S.: you know that one? ;>

"i had a problem and i thought i could use java. now i have a problem factory"

**Comment by WebReflection** [comment]
https://github.com/ungap/custom-elements-builtin#constructor-caveat
