### ISSUE TITLE
rename 'min.js' to 'custom-elements-builtin.min.js' 

### ISSUE THREAD

**Issue by 1aron** [ungap/custom-elements-builtin#7]
We often copy the package file inside node_modules to a directory. Using name of the kit is more formal.

**Comment by WebReflection** [comment]
if you copy you can also copy with the name you prefer, right?

the purpose of `min.js` is to provide the least amount of bytes possible, making the file name the longest ever defeats the purpose of the minification ... I have modules shorter than their name, and anyone copying modules around can copy with whatever convention/name they prefer.

Using `min.js` is everywhere in my modules and nobody complained so far, so I guess this is a won't fix.
