### ISSUE TITLE
Error trying to access class functions

### ISSUE THREAD

**Issue by ilariuss** [ungap/custom-elements-builtin#9]
Hello!

I have the next problem
My class
```
class MyTest extends HTMLDivElement{
     connectedCallback(){
          console.log("test");
     }
     message(){
          alert("hi");
     }
}
customElements.define("my-test", MyTest, {extends :'div'});

Var test = document.createElement('div', { is: 'my-test'});
test.message() <-------------------------------- UNDEFINED
document.appendChild(test); <---------- not even enter in connectedCallback() method
But

var test = MyTest(); <---------------------------- Fail in safari, TypeError: function is not a constructor (evaluating 'super(...args)')
test.message(); <------------- Works on chrome
document.appendChild(test); <-------------- works on chrome
```

Really thank you!

**Comment by WebReflection** [comment]
Are you including the polyfill at all? whenever you are in doubts, use the live test page here:
https://ungap.github.io/custom-elements-builtin/test/

your code works fine in WebKit/Safari, and you can test the transpiler version too in here:
https://ungap.github.io/custom-elements-builtin/test/es5/

> var test = MyTest();

you cannot do that, but it's also wrong, as classes need `new`, or these will fail **everywhere**.

However, you need the procedural way with this polyfill, which is a limitation [well described in the README](https://github.com/ungap/custom-elements-builtin#constructor-caveat).

There's nothing to do for me here, so I'll close this ticket too.
